# Generated by Django 5.2.6 on 2025-09-17 03:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('combustivel_moto', models.BooleanField(default=False, verbose_name='Combustível Moto')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='FechamentoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(unique=True, verbose_name='Data')),
                ('fundo_caixa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fundo de Caixa')),
                ('dinheiro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dinheiro')),
                ('credito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Crédito')),
                ('debito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Débito')),
                ('duplicatas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Duplicatas')),
                ('cheque', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cheque')),
                ('total_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de Venda')),
                ('tipo_dia', models.CharField(choices=[('NORMAL', 'Dia Normal'), ('FERIADO', 'Feriado'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], default='NORMAL', max_length=10, verbose_name='Tipo do Dia')),
            ],
            options={
                'verbose_name': 'Fechamento Diário',
                'verbose_name_plural': 'Fechamentos Diários',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OperacaoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(verbose_name='Data')),
                ('numero_op', models.CharField(choices=[('D1', 'Débito'), ('C0', 'Crédito'), ('C1', 'Crédito à Vista'), ('C2', 'Crédito 2x'), ('C3', 'Crédito 3x'), ('C4', 'Crédito 4x'), ('C5', 'Crédito 5x'), ('CP1', 'Crédito à Vista (Bandeiras Especiais)'), ('CP2', 'Crédito Parcelado (Bandeiras Especiais)')], max_length=10, verbose_name='Nº OP')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Bruto')),
                ('taxa', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Taxa (%)')),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Líquido')),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Desconto')),
            ],
            options={
                'verbose_name': 'Operação de Cartão',
                'verbose_name_plural': 'Operações de Cartão',
                'ordering': ['-data', 'numero_op'],
            },
        ),
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('categoria', models.CharField(choices=[('CASA', 'Despesas da Casa'), ('EMPRESA', 'Despesas da Empresa'), ('PESSOAL', 'Despesas Pessoais')], max_length=20, verbose_name='Categoria')),
                ('subcategoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subcategoria')),
            ],
            options={
                'verbose_name': 'Retirada',
                'verbose_name_plural': 'Retiradas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='TaxaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_op', models.CharField(max_length=10, unique=True, verbose_name='Código OP')),
                ('bandeiras', models.TextField(verbose_name='Bandeiras')),
                ('tipo_bandeira', models.CharField(max_length=50, verbose_name='Tipo Bandeira')),
                ('taxa_percentual', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Taxa (%)')),
                ('dias_compensacao', models.IntegerField(verbose_name='Dias para Compensar')),
            ],
            options={
                'verbose_name': 'Taxa de Cartão',
                'verbose_name_plural': 'Taxas de Cartão',
            },
        ),
        migrations.CreateModel(
            name='Duplicata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Bruto')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicatas', to='api.cliente')),
            ],
            options={
                'verbose_name': 'Duplicata',
                'verbose_name_plural': 'Duplicatas',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='CompraFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='api.fornecedor')),
            ],
            options={
                'verbose_name': 'Compra de Fornecedor',
                'verbose_name_plural': 'Compras de Fornecedores',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='BoletoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Documento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='api.fornecedor')),
            ],
            options={
                'verbose_name': 'Boleto de Compra',
                'verbose_name_plural': 'Boletos de Compra',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ResumoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('mes', models.DateField(verbose_name='Mês')),
                ('receita_vendas', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Receita de Vendas')),
                ('despesas_fornecedor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Despesas com Fornecedor')),
                ('despesas_variaveis', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Despesas Variáveis')),
                ('despesas_casa', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Despesas da Casa')),
                ('despesas_pessoais', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Despesas Pessoais')),
                ('total_liquido', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Líquido')),
                ('aluguel_empresa', models.DecimalField(decimal_places=2, default=1600.0, max_digits=10, verbose_name='Aluguel Empresa')),
                ('honorarios_contador', models.DecimalField(decimal_places=2, default=706.0, max_digits=10, verbose_name='Honorários Contador')),
                ('sistema_alterdata', models.DecimalField(decimal_places=2, default=352.73, max_digits=10, verbose_name='Sistema Alterdata')),
                ('telefonia_internet', models.DecimalField(decimal_places=2, default=240.0, max_digits=10, verbose_name='Telefonia/Internet')),
                ('compras_locais', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Compras Lojas Locais')),
                ('salario_funcionarios', models.DecimalField(decimal_places=2, default=4000.0, max_digits=10, verbose_name='Salário Funcionários')),
                ('desconto_cartao', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto Cartão')),
                ('boletos_duplicatas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Boletos e Duplicatas')),
                ('multas_encargos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multas e Encargos')),
            ],
            options={
                'verbose_name': 'Resumo Mensal',
                'verbose_name_plural': 'Resumos Mensais',
                'ordering': ['-mes'],
                'unique_together': {('mes',)},
            },
        ),
    ]
