# Generated by Django 5.2.6 on 2025-09-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='documento',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
