# Generated by Django 5.2.6 on 2025-09-17 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_fornecedor_documento_fornecedor_cnpj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Despesa Fixa',
                'verbose_name_plural': 'Despesas Fixas',
            },
        ),
        migrations.CreateModel(
            name='VendaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('tipo_venda', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CREDITO', 'Crédito'), ('DEBITO', 'Débito'), ('DUPLICATA', 'Duplicata'), ('CHEQUE', 'Cheque')], max_length=20, verbose_name='Tipo de Venda')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='api.fechamentodiario')),
            ],
            options={
                'verbose_name': 'Venda Diária',
                'verbose_name_plural': 'Vendas Diárias',
            },
        ),
    ]
